// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type CreateUserRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type CreateUserResponse struct {
	UserID               int32    `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserResponse) Reset()         { *m = CreateUserResponse{} }
func (m *CreateUserResponse) String() string { return proto.CompactTextString(m) }
func (*CreateUserResponse) ProtoMessage()    {}
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *CreateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserResponse.Unmarshal(m, b)
}
func (m *CreateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserResponse.Marshal(b, m, deterministic)
}
func (m *CreateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserResponse.Merge(m, src)
}
func (m *CreateUserResponse) XXX_Size() int {
	return xxx_messageInfo_CreateUserResponse.Size(m)
}
func (m *CreateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserResponse proto.InternalMessageInfo

func (m *CreateUserResponse) GetUserID() int32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

type ListUserRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUserRequest) Reset()         { *m = ListUserRequest{} }
func (m *ListUserRequest) String() string { return proto.CompactTextString(m) }
func (*ListUserRequest) ProtoMessage()    {}
func (*ListUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *ListUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUserRequest.Unmarshal(m, b)
}
func (m *ListUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUserRequest.Marshal(b, m, deterministic)
}
func (m *ListUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUserRequest.Merge(m, src)
}
func (m *ListUserRequest) XXX_Size() int {
	return xxx_messageInfo_ListUserRequest.Size(m)
}
func (m *ListUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListUserRequest proto.InternalMessageInfo

type ListUserResponse struct {
	Users                []*User  `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUserResponse) Reset()         { *m = ListUserResponse{} }
func (m *ListUserResponse) String() string { return proto.CompactTextString(m) }
func (*ListUserResponse) ProtoMessage()    {}
func (*ListUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}

func (m *ListUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUserResponse.Unmarshal(m, b)
}
func (m *ListUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUserResponse.Marshal(b, m, deterministic)
}
func (m *ListUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUserResponse.Merge(m, src)
}
func (m *ListUserResponse) XXX_Size() int {
	return xxx_messageInfo_ListUserResponse.Size(m)
}
func (m *ListUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListUserResponse proto.InternalMessageInfo

func (m *ListUserResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

type GetUserDetailRequest struct {
	UserID               int32    `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserDetailRequest) Reset()         { *m = GetUserDetailRequest{} }
func (m *GetUserDetailRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserDetailRequest) ProtoMessage()    {}
func (*GetUserDetailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{5}
}

func (m *GetUserDetailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserDetailRequest.Unmarshal(m, b)
}
func (m *GetUserDetailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserDetailRequest.Marshal(b, m, deterministic)
}
func (m *GetUserDetailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserDetailRequest.Merge(m, src)
}
func (m *GetUserDetailRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserDetailRequest.Size(m)
}
func (m *GetUserDetailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserDetailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserDetailRequest proto.InternalMessageInfo

func (m *GetUserDetailRequest) GetUserID() int32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

type GetUserDetailResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserDetailResponse) Reset()         { *m = GetUserDetailResponse{} }
func (m *GetUserDetailResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserDetailResponse) ProtoMessage()    {}
func (*GetUserDetailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{6}
}

func (m *GetUserDetailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserDetailResponse.Unmarshal(m, b)
}
func (m *GetUserDetailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserDetailResponse.Marshal(b, m, deterministic)
}
func (m *GetUserDetailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserDetailResponse.Merge(m, src)
}
func (m *GetUserDetailResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserDetailResponse.Size(m)
}
func (m *GetUserDetailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserDetailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserDetailResponse proto.InternalMessageInfo

func (m *GetUserDetailResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type UpdateUserDetailRequest struct {
	UserID               int32    `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	User                 *User    `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserDetailRequest) Reset()         { *m = UpdateUserDetailRequest{} }
func (m *UpdateUserDetailRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserDetailRequest) ProtoMessage()    {}
func (*UpdateUserDetailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{7}
}

func (m *UpdateUserDetailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserDetailRequest.Unmarshal(m, b)
}
func (m *UpdateUserDetailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserDetailRequest.Marshal(b, m, deterministic)
}
func (m *UpdateUserDetailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserDetailRequest.Merge(m, src)
}
func (m *UpdateUserDetailRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserDetailRequest.Size(m)
}
func (m *UpdateUserDetailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserDetailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserDetailRequest proto.InternalMessageInfo

func (m *UpdateUserDetailRequest) GetUserID() int32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *UpdateUserDetailRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type UpdateUserDetailResponse struct {
	UserID               int32    `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserDetailResponse) Reset()         { *m = UpdateUserDetailResponse{} }
func (m *UpdateUserDetailResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateUserDetailResponse) ProtoMessage()    {}
func (*UpdateUserDetailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{8}
}

func (m *UpdateUserDetailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserDetailResponse.Unmarshal(m, b)
}
func (m *UpdateUserDetailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserDetailResponse.Marshal(b, m, deterministic)
}
func (m *UpdateUserDetailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserDetailResponse.Merge(m, src)
}
func (m *UpdateUserDetailResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateUserDetailResponse.Size(m)
}
func (m *UpdateUserDetailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserDetailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserDetailResponse proto.InternalMessageInfo

func (m *UpdateUserDetailResponse) GetUserID() int32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

type DeleteUserRequest struct {
	UserID               int32    `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserRequest) Reset()         { *m = DeleteUserRequest{} }
func (m *DeleteUserRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteUserRequest) ProtoMessage()    {}
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{9}
}

func (m *DeleteUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserRequest.Unmarshal(m, b)
}
func (m *DeleteUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserRequest.Marshal(b, m, deterministic)
}
func (m *DeleteUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserRequest.Merge(m, src)
}
func (m *DeleteUserRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteUserRequest.Size(m)
}
func (m *DeleteUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserRequest proto.InternalMessageInfo

func (m *DeleteUserRequest) GetUserID() int32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

type DeleteUserResponse struct {
	UserID               int32    `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserResponse) Reset()         { *m = DeleteUserResponse{} }
func (m *DeleteUserResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteUserResponse) ProtoMessage()    {}
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{10}
}

func (m *DeleteUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserResponse.Unmarshal(m, b)
}
func (m *DeleteUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserResponse.Marshal(b, m, deterministic)
}
func (m *DeleteUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserResponse.Merge(m, src)
}
func (m *DeleteUserResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteUserResponse.Size(m)
}
func (m *DeleteUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserResponse proto.InternalMessageInfo

func (m *DeleteUserResponse) GetUserID() int32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func init() {
	proto.RegisterType((*User)(nil), "proto.User")
	proto.RegisterType((*CreateUserRequest)(nil), "proto.CreateUserRequest")
	proto.RegisterType((*CreateUserResponse)(nil), "proto.CreateUserResponse")
	proto.RegisterType((*ListUserRequest)(nil), "proto.ListUserRequest")
	proto.RegisterType((*ListUserResponse)(nil), "proto.ListUserResponse")
	proto.RegisterType((*GetUserDetailRequest)(nil), "proto.GetUserDetailRequest")
	proto.RegisterType((*GetUserDetailResponse)(nil), "proto.GetUserDetailResponse")
	proto.RegisterType((*UpdateUserDetailRequest)(nil), "proto.UpdateUserDetailRequest")
	proto.RegisterType((*UpdateUserDetailResponse)(nil), "proto.UpdateUserDetailResponse")
	proto.RegisterType((*DeleteUserRequest)(nil), "proto.DeleteUserRequest")
	proto.RegisterType((*DeleteUserResponse)(nil), "proto.DeleteUserResponse")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 423 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xcf, 0x6e, 0xda, 0x40,
	0x10, 0xc6, 0x65, 0x83, 0x11, 0x1d, 0x54, 0x6a, 0xa6, 0x2d, 0x18, 0x17, 0x15, 0xba, 0x27, 0x44,
	0x11, 0x96, 0xdc, 0x56, 0xaa, 0x7a, 0xad, 0xa5, 0x0a, 0xb5, 0x27, 0x23, 0x0e, 0x3d, 0x9a, 0x76,
	0x85, 0x2c, 0x11, 0xdb, 0xf1, 0x9a, 0x5c, 0xa2, 0x5c, 0xf2, 0x0a, 0x79, 0xb4, 0xdc, 0x73, 0xca,
	0x83, 0x44, 0xbb, 0x5e, 0x1b, 0xf0, 0x9f, 0x90, 0x93, 0xe5, 0x9d, 0xf9, 0x7e, 0xdf, 0xee, 0x7c,
	0x03, 0xb0, 0x67, 0x34, 0x5e, 0x44, 0x71, 0x98, 0x84, 0xa8, 0x89, 0x8f, 0x39, 0xda, 0x86, 0xe1,
	0x76, 0x47, 0x2d, 0x2f, 0xf2, 0x2d, 0x2f, 0x08, 0xc2, 0xc4, 0x4b, 0xfc, 0x30, 0x60, 0x69, 0x13,
	0xb1, 0xa1, 0xb9, 0x66, 0x34, 0xc6, 0x2e, 0xa8, 0x4b, 0xc7, 0x50, 0x26, 0xca, 0x54, 0x73, 0xd5,
	0xa5, 0x83, 0x26, 0xb4, 0x39, 0x2a, 0xf0, 0x2e, 0xa8, 0xa1, 0x4e, 0x94, 0xe9, 0x2b, 0x37, 0xff,
	0x27, 0x5f, 0xa1, 0xf7, 0x33, 0xa6, 0x5e, 0x42, 0xb9, 0xd2, 0xa5, 0x97, 0x7b, 0xca, 0x12, 0x1c,
	0x43, 0x93, 0x37, 0x08, 0x44, 0xc7, 0xee, 0xa4, 0xf8, 0x85, 0xe8, 0x10, 0x05, 0x32, 0x07, 0x3c,
	0x56, 0xb1, 0x28, 0x0c, 0x18, 0xc5, 0x3e, 0xb4, 0x78, 0x35, 0xf7, 0x96, 0x7f, 0xa4, 0x07, 0x6f,
	0xfe, 0xf8, 0x2c, 0x39, 0x72, 0x20, 0xdf, 0x40, 0x3f, 0x1c, 0x49, 0xf9, 0x27, 0xd0, 0xb8, 0x80,
	0x19, 0xca, 0xa4, 0x51, 0xb4, 0x4d, 0x2b, 0x64, 0x01, 0xef, 0x7e, 0x51, 0xa1, 0x72, 0x68, 0xe2,
	0xf9, 0xbb, 0xec, 0xc2, 0x75, 0xce, 0xdf, 0xe1, 0x7d, 0xa1, 0x5f, 0x7a, 0x9d, 0x7d, 0xa1, 0x0b,
	0x83, 0x75, 0xf4, 0x5f, 0xbe, 0xf0, 0x45, 0x66, 0x39, 0x53, 0xad, 0x63, 0xda, 0x60, 0x94, 0x99,
	0x67, 0x66, 0xf7, 0x19, 0x7a, 0x0e, 0xdd, 0xd1, 0xd3, 0x7c, 0xea, 0x9a, 0xe7, 0x80, 0xc7, 0xcd,
	0xcf, 0xa3, 0xed, 0x87, 0x06, 0x74, 0x78, 0xe3, 0x8a, 0xc6, 0x57, 0xfe, 0x3f, 0x8a, 0x2b, 0x80,
	0x43, 0xa8, 0x68, 0xc8, 0xfb, 0x97, 0xb6, 0xc3, 0x1c, 0x56, 0x54, 0x52, 0x2b, 0xa2, 0xdf, 0xde,
	0x3f, 0xde, 0xa9, 0x40, 0x34, 0x8b, 0x7b, 0xfc, 0x50, 0x66, 0xf8, 0x1b, 0xda, 0x59, 0xd0, 0xd8,
	0x97, 0xc2, 0xc2, 0x32, 0x98, 0x83, 0xd2, 0xb9, 0xc4, 0x75, 0x05, 0xae, 0x8d, 0x2d, 0x81, 0x63,
	0xb8, 0x81, 0xd7, 0x27, 0x71, 0xe2, 0x07, 0xa9, 0xac, 0x5a, 0x0a, 0x73, 0x54, 0x5d, 0x94, 0xec,
	0xbe, 0x60, 0xeb, 0xd8, 0x15, 0x6c, 0xeb, 0x3a, 0x1d, 0xca, 0x0d, 0x06, 0xa0, 0x17, 0x43, 0xc2,
	0x8f, 0x59, 0x96, 0xd5, 0x1b, 0x61, 0x8e, 0x6b, 0xeb, 0xd2, 0x6c, 0x28, 0xcc, 0xde, 0x9a, 0x05,
	0x33, 0x3e, 0xa0, 0xbf, 0x00, 0x87, 0xcc, 0xf2, 0xa9, 0x97, 0x32, 0xcf, 0xa7, 0x5e, 0x0e, 0x38,
	0x7b, 0xca, 0xac, 0x40, 0xdf, 0xb4, 0x84, 0xe2, 0xcb, 0x53, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc1,
	0x3a, 0x55, 0x4b, 0x49, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
	ListUser(ctx context.Context, in *ListUserRequest, opts ...grpc.CallOption) (*ListUserResponse, error)
	GetUserDetail(ctx context.Context, in *GetUserDetailRequest, opts ...grpc.CallOption) (*GetUserDetailResponse, error)
	UpdateUserDetail(ctx context.Context, in *UpdateUserDetailRequest, opts ...grpc.CallOption) (*UpdateUserDetailResponse, error)
	DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, "/proto.UserService/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ListUser(ctx context.Context, in *ListUserRequest, opts ...grpc.CallOption) (*ListUserResponse, error) {
	out := new(ListUserResponse)
	err := c.cc.Invoke(ctx, "/proto.UserService/ListUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUserDetail(ctx context.Context, in *GetUserDetailRequest, opts ...grpc.CallOption) (*GetUserDetailResponse, error) {
	out := new(GetUserDetailResponse)
	err := c.cc.Invoke(ctx, "/proto.UserService/GetUserDetail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateUserDetail(ctx context.Context, in *UpdateUserDetailRequest, opts ...grpc.CallOption) (*UpdateUserDetailResponse, error) {
	out := new(UpdateUserDetailResponse)
	err := c.cc.Invoke(ctx, "/proto.UserService/UpdateUserDetail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error) {
	out := new(DeleteUserResponse)
	err := c.cc.Invoke(ctx, "/proto.UserService/DeleteUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	ListUser(context.Context, *ListUserRequest) (*ListUserResponse, error)
	GetUserDetail(context.Context, *GetUserDetailRequest) (*GetUserDetailResponse, error)
	UpdateUserDetail(context.Context, *UpdateUserDetailRequest) (*UpdateUserDetailResponse, error)
	DeleteUser(context.Context, *DeleteUserRequest) (*DeleteUserResponse, error)
}

// UnimplementedUserServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (*UnimplementedUserServiceServer) CreateUser(ctx context.Context, req *CreateUserRequest) (*CreateUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (*UnimplementedUserServiceServer) ListUser(ctx context.Context, req *ListUserRequest) (*ListUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUser not implemented")
}
func (*UnimplementedUserServiceServer) GetUserDetail(ctx context.Context, req *GetUserDetailRequest) (*GetUserDetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserDetail not implemented")
}
func (*UnimplementedUserServiceServer) UpdateUserDetail(ctx context.Context, req *UpdateUserDetailRequest) (*UpdateUserDetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUserDetail not implemented")
}
func (*UnimplementedUserServiceServer) DeleteUser(ctx context.Context, req *DeleteUserRequest) (*DeleteUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUser not implemented")
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserService/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ListUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ListUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserService/ListUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ListUser(ctx, req.(*ListUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUserDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUserDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserService/GetUserDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUserDetail(ctx, req.(*GetUserDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateUserDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateUserDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserService/UpdateUserDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateUserDetail(ctx, req.(*UpdateUserDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserService/DeleteUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).DeleteUser(ctx, req.(*DeleteUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _UserService_CreateUser_Handler,
		},
		{
			MethodName: "ListUser",
			Handler:    _UserService_ListUser_Handler,
		},
		{
			MethodName: "GetUserDetail",
			Handler:    _UserService_GetUserDetail_Handler,
		},
		{
			MethodName: "UpdateUserDetail",
			Handler:    _UserService_UpdateUserDetail_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _UserService_DeleteUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
